### ISSUE TITLE
about train

### ISSUE THREAD

**Issue by JYC1012** [Dai-Wenxun/MotionLCM#16]
![image](https://github.com/user-attachments/assets/a1056ad1-e773-486f-8f5f-f3b24a447a89)

Hello, I am very interested in your work. I am trying to train Motionlcm myself using commands
python -m train_motion_control --cfg configs/motionlcm_control.yaml
An error was found as shown in the image above，It seems that during the validation phase after the first epoch of training, there was an error when calculating the FID. I did not modify the code. How can I solve this problem, Looking forward to your reply, thank you!

**Comment by Dai-Wenxun** [comment]
I had this issue before. It is not the problem with the MotionLCM code. This issue comes from the version of scipy. Could you please check the version. This version I used in req.txt is here:
![image](https://github.com/user-attachments/assets/c9f99913-0055-4920-af48-de2a7832301f)

There is a similar issue:
https://github.com/bioinf-jku/TTUR/issues/4#issuecomment-1907223546

**Comment by JYC1012** [comment]
Thank you for your reply. I have checked that the previous version of Scipy was 1.11.2, but when I downgraded it to 1.11.1, the same issue still persists.
![image](https://github.com/user-attachments/assets/04a7ecbf-7ba0-4542-8ba9-bb94fce20cf7)

And what I need to correct is that the command I am running is:
python -m train_motionlcm --cfg configs/motionlcm_t2m.yaml

**Comment by JYC1012** [comment]
I reinstalled Scipy and Numpy, and lowered the Scipy version to 1.11.1, which solved the problem

Thank you for your prompt response
