### ISSUE TITLE
Do the existing motion representations have any extra features that aren't really needed?

### ISSUE THREAD

**Issue by LutherLin** [Dai-Wenxun/MotionLCM#24]
Many model’s performance exceed the real motions, this may be due to outdated evaluators. 

I found a study( https://arxiv.org/abs/2411.16575 ) that suggests， in HumanML3D(263 dims) only the first 67 dims from this overparameterized representation are used to produce final human motion, making the remaining components redundant.

Could this data redundancy be why the performance is better than real-motions?

**Comment by shunlinlu** [comment]
This is due to the wrong formulations of rotations in HumanML3D. We can not convert the local rotations in HumanML3D back and use it into software, like blender, i.e. the calculations of the rotations are wrong. Furthermore, the way of using positions is not suitable for downstream applications. This format needs IK operations, which may involve more errors. We are revisiting the HumanML3D representation and correcting the rotation representation. In our representation, either positions or rotations can be converted to the same BVH. The new representation will be trained in our new work [ScaMo](https://arxiv.org/abs/2412.14559) in the future  and the following work. Please stay tuned.

**Comment by Dai-Wenxun** [comment]
metric doesn't matter, quality matters.
