### ISSUE TITLE
About Dependences

### ISSUE THREAD

**Issue by XingliangJin** [Dai-Wenxun/MotionLCM#8]
I want to know if the dependencies in deps/ are exactly the same as those in the original mld?

**Comment by Dai-Wenxun** [comment]
Almost the same. 

When preparing the `deps/` directory for mld, I found that some unnecessary files are included in the downloaded zips. For example, `deps/glove` is wrongly included in `deps/t2m/` and is ignored by the authors in their preparation part. Moreover, there are some unnecessary smpl files included in `deps/smpl_models`.  

To clean up these dependencies, I reorganize the deps and upload all deps to my [google drive](https://drive.google.com/drive/folders/1SIhb6srXWS0PNvZ2fs40QiE3Rk764u6z?usp=sharing). Thus, I recommend you to follow the `Quick Start` to finish the preparation of deps.

Note that, the text encoder used in motionlcm is `t5` instead of `clip` in the original mld, please run the [prepare_t5.sh](https://github.com/Dai-Wenxun/MotionLCM/blob/main/prepare/prepare_t5.sh). If encounter any network-related issues, you can manually download the checkpoints and configs from [sentence-t5-large](https://huggingface.co/sentence-transformers/sentence-t5-large/tree/main). Please ensure that you download these files into the `deps/sentence-t5-large`.

![image](https://github.com/Dai-Wenxun/MotionLCM/assets/58767402/7dcfab5a-0085-4d47-85ce-719a66bbfaf9)

**Comment by XingliangJin** [comment]
Thank you for your detailed and thorough explanation！

**Comment by LinghaoChan** [comment]
> Thank you for your detailed and thorough explanation！

@XingliangJin Thanks for your question. As you mentioned the difference between MLD and MotionLCM. One of the differences is the text encoder. Our MotionLCM takes the `t5` as the text encoder as an improved baseline. I also suggest you have a try on our text-motion-aligned text encoder in my [HumanTOMATO](https://lhchen.top/HumanTOMATO/) project (ICML-24).
